### ISSUE TITLE
Update to Microsoft.NETCore.App 2.0 \ NETStandard.Library 2.0.0

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Coherence#166]
| Repository | netcoreapp2.0 | net46 | net461 \ NS.Library 2.0.0 |
| -----------| --------------| ----- | ------ |
| Antiforgery | :heavy_check_mark: | ✔️  |  |
| AzureIntegration | :heavy_check_mark: | ✔️  |  |
| BasicMiddleware | :heavy_check_mark: | ✔️  |  |
| BrowserLink | ✔️ | ✔️ |  |
| Caching | :heavy_check_mark: | ✔️  |  |
| Common | :heavy_check_mark: | ✔️ |  |
| Configuration | :heavy_check_mark: | ✔️  |  |
| CORS | :heavy_check_mark: | ✔️  |  |
| DataProtection | :heavy_check_mark: | ✔️ |  |
| DependencyInjection | :heavy_check_mark: | :heavy_check_mark:  |   |
| Diagnostics | :heavy_check_mark: | ✔️   |  |
| DotNetTools | :heavy_check_mark: | ✔️ |  |
| EntityFramework | :heavy_check_mark: | ✔️ |  |
| Entropy | :heavy_check_mark: |:heavy_check_mark:  |  |
| EventNotification | :heavy_check_mark: | ✔️ |  |
| FileSystem | :heavy_check_mark: | ✔️ |  |
| Hosting | :heavy_check_mark: | ✔️ |   |
| HtmlAbstractions | :heavy_check_mark: | ✔️  |  |
| HttpAbstractions | :heavy_check_mark:| ✔️  |  |
| HttpSysServer | :heavy_check_mark: | ✔️  |  |
| Identity | :heavy_check_mark:  | :heavy_check_mark: |  |
| IdentityService |:heavy_check_mark:  |:heavy_check_mark:  |  |
| IISIntegration | :heavy_check_mark: | ✔️ |  |
| JsonPatch | :heavy_check_mark: |  |  |
| KestrelHttpServer | :heavy_check_mark: | ✔️ |  |
| Localization | :heavy_check_mark: | :heavy_check_mark: |  |
| Logging | :heavy_check_mark: | ✔️  |  |
| MetaPackages |:heavy_check_mark:  |:heavy_check_mark:  |  |
| Microsoft.Data.Sqlite | :heavy_check_mark: |  |  |
| MusicStore | :heavy_check_mark: | :heavy_check_mark:  | In progress |
| Mvc | :heavy_check_mark: | :heavy_check_mark:  |  |
| MvcPrecompilation | :heavy_check_mark: | ✔️ |  |
| Options | :heavy_check_mark: | ✔️ |  |
| PlatformAbstractions | :heavy_check_mark: |  |  |
| Proxy | :heavy_check_mark: |:heavy_check_mark:  |  |
| Razor | ✔️ | ✔️ |  |
| ResponseCaching | :heavy_check_mark: | ✔️   |  |
| Routing | :heavy_check_mark: | ✔️  |  |
| Scaffolding | :heavy_check_mark: | ✔️  |  |
| Security | :heavy_check_mark:  |:heavy_check_mark: |  |
| ServerTests | :heavy_check_mark: | ✔️ |  |
| Session | :heavy_check_mark: | :heavy_check_mark:  |  |
| SignalR | :heavy_check_mark: | ✔️  |  |
| StaticFiles | :heavy_check_mark:  |:heavy_check_mark:  |  |
| Testing | :heavy_check_mark: | ✔️  |  |
| WebSockets |:heavy_check_mark:  | :heavy_check_mark: |  |

## Issues:
* [*] ~~https://github.com/dotnet/standard/issues/200~~
* [x] ?? https://github.com/dotnet/standard/issues/201 -> https://github.com/dotnet/corefx/issues/16152
* [x] ~~Re-enable Razor tests - https://github.com/aspnet/Razor/issues/1003~~
* [ ] Had to skip standalone tests on crossplat in MusicStore after upgrading to new CLI. https://github.com/aspnet/MusicStore/issues/761
* [ ] https://github.com/aspnet/Identity/issues/1141
* [ ] LocalDb does not work - https://github.com/dotnet/corefx/issues/17166
* [ ] https://github.com/aspnet/Security/issues/1156
* [ ] https://github.com/aspnet/Entropy/issues/210
* [ ] https://github.com/aspnet/Mvc/issues/6005
* [ ] https://github.com/aspnet/MusicStore/issues/763
* [ ] https://github.com/aspnet/Diagnostics/issues/354
* [ ] https://github.com/dotnet/cli/issues/6129 
* [ ] https://github.com/aspnet/Identity/issues/1153

**Comment by pranavkm** [comment]
cc @pakrym

**Comment by dougbu** [comment]
See also @natemcmaster's comment from https://github.com/aspnet/Mvc/pull/5852#discussion_r102803250
> re: `<PackageReference Include="Microsoft.Extensions.DependencyModel" Version="1.1.0-*" />`
There is a 2.0.0 version being built...https://github.com/dotnet/core-setup/blob/master/src/Microsoft.Extensions.DependencyModel/. Let's add that to the list of things we upgrade when we move everything to netstandard2.0 / .NET Core 2.0.

**Comment by pranavkm** [comment]
cc @kichalla

**Comment by muratg** [comment]
:eyes:

**Comment by Eilon** [comment]
FYI to those watching, @NTaylorMullen is investigating moving the Razor repo to NETStandard.Library 2.0.0. He had no issues with that in VS2017 RTM.

He's also now investigating what happens if we add a `netstandard20` TFM, which is where we think the pain points in VS2017 are (command line should work fine).

**Comment by NTaylorMullen** [comment]
I was able to upgrade Razor without problem to `netstandard2.0` TFM. Here's the steps I took:

- Downloaded/installed the latest CLI (005685).
- Modified our `cli.version` file to point to new CLI
- Set the following env variable `$env:MSBuildSdksPath="C:\Users\nimullen\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005685\Sdks"`
- Open VS (15.0.0+26228.12) with the env variable set.

Here's the various things I did as verification:
- Open a clean Razor.sln in VS.
- Open a pre-built/restored Razor.sln in VS.
- Re-build
- Build single
- Restore
- Run all tests
- Edit C# files.
- Close Razor.sln

Only thing I ran into (has always happened) was this guy: https://github.com/dotnet/project-system/issues/1554 - **SkipCompilerExecution and ProvideCommandLineArgs issue.**. It's been known about for a while.

Let me know if there's any other scenarios people think I should try.

**Comment by pranavkm** [comment]
Were you able to build from the cmdline with the env variable set? I had trouble building from the command line with it set. Also, presumably this did not involve replacing `net46` -> `netstandard2.0` in a src project and updating tests to `net461`?

**Comment by NTaylorMullen** [comment]
> Were you able to build from the cmdline with the env variable set? I had trouble building from the command line with it set. Also, presumably this did not involve replacing net46 -> netstandard2.0 in a src project and updating tests to net461?

I was able to do a `./build` successfully.

**Comment by Eilon** [comment]
Moving this bug to preview2 since we've done everything we plan to do for preview1.
